config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  devise_for :users
  resources :posts
  root "posts#index"

  get '/about', to: 'pages#about'


end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 3}
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC') 
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post 
		else 
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit 
		@post = Post.find(params[:id])
	end

	def update 
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private 
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="navbar">
		<div id="homepage_link">
			<%= link_to "Home", root_path %><br>
			<%= link_to "About Me", about_path %><br>
		</div>
		<% if !user_signed_in? %>
			<%= link_to "Sign In", login_path %><br>
		<% end %>
	</div>

	<div id"main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>
			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"> <%= link_to "New Post", new_post_path %></button>
					<button class="button"><%= link_to "Log Out", logout_path %></button>
				</div>
			<% end %>
		</div>
	

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
Hi, my name is Peter Manhart, I am just learning Rails, and this blog is terrible! 

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
	<% @posts.each do |post| %>
		<div class="post">
			<h2 class="title"><%= link_to post.title, post %></h2>
			<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Written <%= time_ago_in_words(@post.created_at) %> Ago
		<% if user_signed_in? %>
			| <%= link_to "Edit", edit_post_path(@post) %>
			| <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %> 
		<% end %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>
</div>